USE [master]
GO

/****** Object:  Database [ShufflepuffBang]    Script Date: 4/5/2017 5:36:55 PM ******/
CREATE DATABASE [ShufflepuffBang]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'ShufflepuffBang', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\DATA\ShufflepuffBang.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'ShufflepuffBang_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\DATA\ShufflepuffBang_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [ShufflepuffBang] SET COMPATIBILITY_LEVEL = 130
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [ShufflepuffBang].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [ShufflepuffBang] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [ShufflepuffBang] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [ShufflepuffBang] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [ShufflepuffBang] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [ShufflepuffBang] SET ARITHABORT OFF 
GO

ALTER DATABASE [ShufflepuffBang] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [ShufflepuffBang] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [ShufflepuffBang] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [ShufflepuffBang] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [ShufflepuffBang] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [ShufflepuffBang] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [ShufflepuffBang] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [ShufflepuffBang] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [ShufflepuffBang] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [ShufflepuffBang] SET  DISABLE_BROKER 
GO

ALTER DATABASE [ShufflepuffBang] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [ShufflepuffBang] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [ShufflepuffBang] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [ShufflepuffBang] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [ShufflepuffBang] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [ShufflepuffBang] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [ShufflepuffBang] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [ShufflepuffBang] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [ShufflepuffBang] SET  MULTI_USER 
GO

ALTER DATABASE [ShufflepuffBang] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [ShufflepuffBang] SET DB_CHAINING OFF 
GO

ALTER DATABASE [ShufflepuffBang] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [ShufflepuffBang] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [ShufflepuffBang] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [ShufflepuffBang] SET QUERY_STORE = OFF
GO

USE [ShufflepuffBang]
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [ShufflepuffBang] SET  READ_WRITE 
GO

USE [ShufflepuffBang]
GO

/****** Object:  Table [dbo].[Customer]    Script Date: 4/5/2017 5:37:10 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Customer](
	[CustomerId] [int] IDENTITY(1,1) NOT NULL,
	[Name] [varchar](50) NULL,
	[StreetAddress] [varchar](250) NULL,
	[City] [varchar](250) NULL,
	[State] [varchar](250) NULL,
	[Zip] [int] NULL,
	[Phone] [bigint] NULL,
 CONSTRAINT [PK_Customer] PRIMARY KEY CLUSTERED 
(
	[CustomerId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

USE [ShufflepuffBang]
GO

/****** Object:  Table [dbo].[Invoice]    Script Date: 4/8/2017 11:45:43 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Invoice](
	[InvoiceId] [int] IDENTITY(1,1) NOT NULL,
	[PaymentId] [int] NULL
) ON [PRIMARY]

GO

USE [ShufflepuffBang]
GO

/****** Object:  Table [dbo].[OrderLine]    Script Date: 4/5/2017 5:37:47 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[OrderLine](
	[OrderLineId] [int] IDENTITY(1,1) NOT NULL,
	[InvoiceId] [int] NULL,
	[ProductId] [int] NULL,
	[Quantity] [int] NULL,
 CONSTRAINT [PK_OrderLine] PRIMARY KEY CLUSTERED 
(
	[OrderLineId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

USE [ShufflepuffBang]
GO

/****** Object:  Table [dbo].[Payment]    Script Date: 4/5/2017 5:38:00 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Payment](
	[PaymentId] [int] NOT NULL,
	[Type] [varchar](250) NULL,
	[CustomerId] [int] NULL,
	[AccountNumber] [int] NOT NULL,
 CONSTRAINT [PK_Payment] PRIMARY KEY CLUSTERED 
(
	[PaymentId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

USE [ShufflepuffBang]
GO

/****** Object:  Table [dbo].[Product]    Script Date: 4/5/2017 5:38:28 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Product](
	[ProductId] [int] IDENTITY(1,1) NOT NULL,
	[Name] [varchar](250) NULL,
	[Price] [money] NULL,
 CONSTRAINT [PK_Product] PRIMARY KEY CLUSTERED 
(
	[ProductId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

